### ISSUE TITLE
Consider using SafeHandle

### ISSUE THREAD

**Issue by nietras** [mdabros/XGBoostSharp#30]
For all native IntPtr handles. PInvoke supports usage, and this will address lack of finalizer in several places.

**Comment by mdabros** [comment]
Thanks @nietras! - Will do. I have done some cleanup, but some is definitely still missing :-). As always, you are also more than welcome to contribute if you have time to spare.

**Comment by mdabros** [comment]
@nietras I have added SafeHandles for use in DMatrix and Booster here https://github.com/mdabros/XGBoostSharp/pull/31. If you have time at some point please give it a look, and I will fix any comments in a separate PR.

**Comment by nietras** [comment]
Checkout the end of https://blog.benoitblanchon.fr/safehandle/ in particular you can change DllImport too etc.
