### ISSUE TITLE
Unable to start project due to version issue

### ISSUE THREAD

**Issue by DanielZuerrer** [mdabros/XGBoostSharp#40]
I tried setting up a minimal project to try out the library. Unfortunately the console application does not start due to an issue with the XGBoostSharp assembly.

Here is the project setup:

**.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libxgboost-2.0.3-osx-x64" Version="1.0.0" />
    <PackageReference Include="XGBoostSharp" Version="0.4.5" />
  </ItemGroup>

</Project>
```

**Program.cs**
```c#
using XGBoostSharp;

using var classifier = new XGBClassifier(maxDepth: 3, learningRate: 0.1f, nEstimators: 100);

Console.WriteLine("Hello, World!");

``` 
When running the app I get the following error:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'XGBoostSharp, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'XGBoostSharp, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'

Process finished with exit code 134.
```

I'm running the app on an M1 Pro CPU under macOS 15.1.1. .NET SDK 8.0.403, Runtime .NET Core 8.0.10

I would appreciate if you can give me any pointers to mistakes on my side or if there is some misconfiguration of the NuGet.

**Comment by mdabros** [comment]
Hi @DanielZuerrer 

Sadly I only have a windows machine to test on locally. Here the same minimal project runs with no issues using either the xgboostsharp package or the xgboostsharp-cpu package. The package is tested on macos-13 via CI and github actions. This is the only macos test I can do at this time. It is weird though that it is the dotnet package that can't be found. I would have expected potential macos issues to come from the native libxgboost package. How does your build folder look? Is the `XGBoostSharp.dll` present? On my windows machine it looks like this:

![image](https://github.com/user-attachments/assets/58dbe235-8e4b-4dec-bec8-8c04f5efa037)

**Comment by DanielZuerrer** [comment]
Thank @mdabros for the response. The `XGBoostSharp.dll` is present, the build folder looks identical to yours. We could also try it on a windows machine of a colleague and there everything worked without any issues. This leads me to believe it's an issue with the underlying `libxgboost.dylib` not matching the ARM architecture.

Would it be possible for you to provide an additional NuGet for ARM macs in addition to the three native x64 libraries? I have already checked the wheels you listed in the NuGet readme and there is an mac arm64 version of xgboost.

**Comment by mdabros** [comment]
@DanielZuerrer Sounds like that could be the problem. Yes, I can try adding a package for arm64 if there is a native lib available in the wheels. I will try to add it when/if time permits during this week or the next. I will get back to you here once it is available. If possible I will try to test the package via CI, but if not, you might have to do a couple of tests locally to ensure if works :).

**Comment by mdabros** [comment]
@DanielZuerrer I have added the native package for osx arm64. See https://www.nuget.org/packages/libxgboost-2.0.3-osx-arm64/.  You are welcome to try and test it with the current release. However, I believe it will not work before XGBoostSharp is build for AnyCPU instead of specific x64. I have made those changes in this PR: https://github.com/mdabros/XGBoostSharp/pull/41. I I have tested the package for osx arm64 using CI sucessfully, and it should work with the next release. However, I was unable to get get the CI running with osx arm64 together with the other packages and runtimes, so it is disabled in the CI for now. See the PR for more details.

I will create a new release containing the AnyCPU build during next week.

**Comment by DanielZuerrer** [comment]
@mdabros thank you, I'm happy to see you got to it so quickly. You're correct, the sample app with the osx arm64 package still has the same issue. However, I cloned this repository and added the sample console app to the solution directly. With the latest version from PR #41 it now works. Thank you for the quick updates!

**Comment by mdabros** [comment]
@DanielZuerrer Sounds good, and thanks for testing!

**Comment by mdabros** [comment]
@DanielZuerrer Version 0.4.6 has been released with the changes mentioned above. So you can get this version via nuget now. https://github.com/mdabros/XGBoostSharp/releases/tag/v0.4.6

**Comment by DanielZuerrer** [comment]
@mdabros thank you again, that's great news. I got it running in our project and everything looks good!

One small issue I've found is that the `libxgboost-2.0.3-osx-arm64` package does not seem to play well with class library projects. This arrangement of dependencies does not work:

![image](https://github.com/user-attachments/assets/b7e42554-68ce-41a7-bca5-9081e115535f)
 
Building the solution gives this error:

`Error MSB3030 : Could not copy the file "bin/Debug/net8.0//runtimes/osx-arm64/native/libomp.dylib" because it was not found.`

However in this arrangement it does work:

![image](https://github.com/user-attachments/assets/38f42e42-8172-488c-a5d8-44710a2a2dc5)

For us it's fine to just have the `libxgboost-2.0.3-osx-arm64` dependency in the API project, it's just not super nice with the dependencies going the "wrong way". So it's definitely nothing urgent, but if you know where the issue could we would appreciate any updates. Probably also something for a different issue as we got everything running now.

Thanks again for all the support and quick updates!

**Comment by mdabros** [comment]
@DanielZuerrer Sounds good you got things running. It would be great to close this issue, and open a new one with the dependency issue. I will try to take a look at it when time permits. Thanks for bringing in the issues, so we can have them fixed.

**Comment by DanielZuerrer** [comment]
I finally got around to making the new issue here: #45 

As mentioned, it's definitely not urgent as the workaround is okay for us.
